spring.application.name=mtitek-spring-mongodb

spring.mongodb.host=localhost
spring.mongodb.port=27017
#spring.mongodb.username=
#spring.mongodb.password=
spring.mongodb.database=mtitek-spring-mongodb

de.flapdoodle.mongodb.embedded.version=7.0.2

logging.level.org.springframework.jdbc.core.JdbcTemplate=debug